FROM node:20.11.1-alpine3.18

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm cache clean --force \
  rm -rf node_modules \
  npm install

COPY . .

EXPOSE 3003

CMD ["npm", "run", "start:dev"]